AWSTemplateFormatVersion: 2010-09-09
Description: dzarquitectura project template
Resources:
  MainVpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'false'
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: MainVpc
        - Key: Project
          Value: dzarq
        - Key: Ceco
          Value: dzImprovements
  TheIGW:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Project
          Value: dzarq
        - Key: Ceco
          Value: dzImprovements
Outputs:
  VpcName:
    Description: Vpc Name
    Value: !Ref MainVpc
